version: "3.1"
services:
  hlds:
    image: hlds-amxmodx:latest
    build:
      context: .
      dockerfile: image/hlds-amxmodx/Dockerfile
      args:
        - steam_user=${STEAM_USER:-anonymous}
        - steam_password=${STEAM_PASSWORD:-''}
        - amxmod_version=1.8.2
  server:
    image: cs16-server:$IMAGE_TAG
    build:
      context: .
      dockerfile: image/cs16-server/Dockerfile
    environment:
      - SERVER_NAME=${SERVER_NAME:-CS 1.6 Server}
      - START_MAP=${START_MAP:-de_dust2}
      - MAXPLAYERS=${MAXPLAYERS:-32}
      - ADMIN_IP
      - ADMIN_NAME
      - ADMIN_PASSWORD
      - SERVER_PASSWORD
      - YAPB_ENABLED
      - YAPB_PASSWORD
      - CSDM_MODE
    restart: always
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
